### ISSUE TITLE
Unsound usages of unsafe implementation from `buf` to `$t`

### ISSUE THREAD

**Issue by llooFlashooll** [r-bk/rsdns#4]
Hi, I am scanning the rsdns in the latest version with my own static analyzer tool.

Unsafe conversion found at: src/bytes/macros.rs#L5
``` rust
macro_rules! r_be {
    ($self:ident, $t:ty) => {{
        if $self.len() >= std::mem::size_of::<$t>() {
            let buf = unsafe { $self.buf.get_unchecked($self.pos..) };
            let ptr = buf.as_ptr() as *const $t;
            let v = unsafe { ptr.read_unaligned() };
            $self.pos += std::mem::size_of::<$t>();
            Ok(v.to_be())
        } else {
            Err($self.bound_error())
        }
    }};
}
```

This unsound implementation would create a misalignment issues if the type size of `buf` is smaller than the type size of `$t`.

This would potentially cause [undefined behaviors](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) in Rust. If we further manipulate the problematic converted types, it would potentially lead to different consequences such as access out-of-bound. I am reporting this issue for your attention.

**Comment by r-bk** [comment]
@llooFlashooll

Thanks for reporting this!

I am not completely understanding the possible UB scenario.

The `r_be` macro (and its counterparts) are private to the `bytes` package and are used only in the implementation of `Cursor` which defines the buffer as `buf: &'a [u8]`.

This line ensures that the number of bytes in the buffer is sufficient to read type `$t`
`if $self.len() >= std::mem::size_of::<$t>()`.

And this line reads the pointer unaligned `let v = unsafe { ptr.read_unaligned() };`.

The macro is used to read `u16`, `u32` and `u128`. The size of these types is indeed larger than `u8`. However, given that the pointer is explicitly read unaligned, where is the misalignment issue that you mention?

Can you elaborate on the possible misalignment? or undefined behavior?

**Comment by r-bk** [comment]
@llooFlashooll 

Did you mean that the line `let ptr = buf.as_ptr() as *const $t;` creates a temporary unaligned reference of type `&t`, which is the UB?
If yes, can you point me to the relevant documentation? Cause the documentation [1] of `as_ptr` doesn't mention that. The examples of "On `packed` structs" in [2] do not involve calling `as_ptr`.

[1] https://doc.rust-lang.org/std/primitive.slice.html#method.as_ptr
[2] https://doc.rust-lang.org/std/ptr/fn.read_unaligned.html#on-packed-structs

**Comment by r-bk** [comment]
@llooFlashooll 

`ptr` is created as a temporary unaligned Pointer, not Reference (correct me if I am wrong here). If it was an unaligned Reference it would be UB. According to documentation that you have included above [1] creation of an unaligned Pointer itself isn't a UB. This together with `read_unaligned` ensures no UB.

You are right, the value being read may output meaningless data. However, this is not related to using unsafe Rust or using a misaligned pointer. For example, you can read meaningless data from a file on disk even in a program written in completely safe Rust `#![forbid(unsafe_code)]`.

[1] https://doc.rust-lang.org/reference/behavior-considered-undefined.html#places-based-on-misaligned-pointers
