### ISSUE TITLE
Fails to compile when doing a query in a tokio task

### ISSUE THREAD

**Issue by sophacles** [r-bk/rsdns#5]
Using tokio with the `rt` (with or without `rt-multi-thread`) and trying to do a rsdns query within a spawned task, the code fails to compile.

There's a lot warnings and so on in the output, but I think it comes down to: `ClientImpl` uses a `RefCell<Vec<u8>>` which is not `Send`.

Example code that fails to compile:

Cargo.toml:
```
rsdns = { version = "0.18.0", features = ["net-tokio"] }
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread",  "net", ] }
```
(Note: I did some testing with multiple tokio versions, all with the same fundamental issue)

main.rs:
```rust
use std::net::{Ipv4Addr, SocketAddr};
use std::str::FromStr;

use rsdns::{
    clients::{tokio::Client, ClientConfig},
    records::{data::A, Class},
};

async fn do_query(host: String) -> (String, Ipv4Addr) {
    let config = ClientConfig::with_nameserver(SocketAddr::from_str("1.1.1.1:53").unwrap());
    let mut client = Client::new(config).await.unwrap();
    let res = client
        .query_rrset::<A>(host.as_str(), Class::IN)
        .await
        .unwrap();

    (host, res.rdata.first().unwrap().address)
}

#[tokio::main]
async fn main() {
    let mut handles = Vec::new();
    for i in [
        "www.google.com".to_string(),
        "www.cloudflare.com".to_string(),
    ] {
        handles.push(tokio::spawn(async move { do_query(i).await }));
    }

    for handle in handles {
        let (host, ip) = handle.await.unwrap();
        println!("{}: {}", host, ip);
    }
}
```

**Comment by r-bk** [comment]
@sophacles 

Thanks for reporting this!
I have reproduced the issue in an internal test.
I will remove `RefCell` from clients' implementation to make them `Send`.

**Comment by sophacles** [comment]
Wow, that was fast - Thanks! 

The fix is confirmed to work in all of:
 * the example above
 * my experimenting
 * the actual project I'm using this for

Do you plan on cutting a release with this fix soon?

**Comment by r-bk** [comment]
@sophacles 

Thanks for the confirmation!
Yes, I plan to release v0.19.0 during this weekend.

**Comment by sophacles** [comment]
Very cool,  I look forward to it. Thanks again for fixing this so quick!

**Comment by r-bk** [comment]
@sophacles `v0.19.0` is out, the fix included.
